version: "3.7"
services:
  db:
    container_name: PizzaGraphSQL
    image: exoplatform/sqlserver:2017-CU8
    environment:
      - SA_PASSWORD=PizzaGraphQL123+
      - SQLSERVER_DATABASE=PizzaGraphQL
      - SQLSERVER_USER=PizzaGraphQL
      - SQLSERVER_PASSWORD=PizzaGraphQL123+
    ports:
      - "1433:1433"
  pizza-management:
    build: ./services/pizza-management
    image: pizza-management:latest
    ports:
      - "8080:80"
    depends_on:
      - db
  pizza-commands:
    build: ./services/pizza-commands
    image: pizza-commands:latest
    ports:
      - "8081:80"
    depends_on:
      - db
  pizza-pricing:
    build: ./services/pizza-pricing
    image: pizza-pricing:latest
    ports:
      - "8082:80"
    depends_on:
      - db
  identity-server:
    build: ./identity-server
    image: identity-server:latest
    ports:
      - "8090:80"
